version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: git submodule -q update --init
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: 'PInvokeSerialPort\bin\**\*.nupkg'
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master
    appveyor_repo_tag: true 